ojo_deduplication_num_units: null
ojo_deduplication_unit_type: null
ojo_s3_file_adverts_ojd_daps_extract: "s3://open-jobs-lake/latest_output_tables/adverts_ojd_daps_extract.parquet"
ojo_s3_file_descriptions: "s3://open-jobs-lake/latest_output_tables/descriptions.parquet"
ojo_s3_file_salaries: "s3://open-jobs-lake/latest_output_tables/salaries_ojd_daps_extract.parquet"
ojo_s3_file_locations: "s3://open-jobs-lake/latest_output_tables/locations_ojd_daps_extract.parquet"
ojo_s3_file_skills: "s3://open-jobs-lake/latest_output_tables/skills_ojd_daps_extract.parquet"
ojo_random_sample_size: 100000

job_adverts:
  job_id_key: "id"
  job_text_key: "job_text"
  job_title_key: "job_title"
  company_name_key: "company_name"
  data_folder_name: "outputs/data/"
skills:
  skills_config_name: "extract_green_skills_esco"
  load_skills: False # If False it doesn't matter what skills_output is
  load_skills_embeddings: False # If False it doesn't matter what skill_embeddings_output is
  load_taxonomy_embeddings: True # If False it doesn't matter what green_tax_embedding_path is
  skills_output: "outputs/data/green_skill_lists/20230914/skills_data_ojo_mixed.json" # Set if load_skills is True
  skill_embeddings_output: "outputs/data/green_skill_lists/20230914/extracted_skills_embeddings.json" # Set if load_skills_embeddings is True
  green_tax_embedding_path: "outputs/data/green_skill_lists/green_esco_embeddings_20231129.json" # Set if load_taxonomy_embeddings is True
  green_skills_classifier_model_file_name: "outputs/models/green_skill_classifier/green_skill_classifier_20231129.joblib"
occupations:
  local: False
  embeddings_output_dir: "outputs/data/green_occupations/soc_matching/"
  batch_size: 500
  match_top_n: 10
  sim_threshold: 0.67
  top_n_sim_threshold: 0.5
  minimum_n: 3
  minimum_prop: 0.5
  save_embeds: True
industries:
  verbose: True
  multi_process: False
  local: False
  sic_comp_desc_path: "20230911_sic_company_descriptions_dict_production_True_chunksize_50.json"
  sic_comp_desc_embeds_path: "20230911_sic_company_descriptions_embeds_production_True_chunksize_50.json"
  model_path: "nestauk/jobbert-base-cased-compdecs"
  bert_model_name: "all-MiniLM-L6-v2"
  faiss_k: 100
  sic_levels: [2, 3, 4]
  closest_distance_threshold: 0.48
  majority_sic_threshold: 0.3
