ojo_deduplication_num_units: null
ojo_deduplication_unit_type: null
ojo_s3_file_adverts_ojd_daps_extract: "s3://open-jobs-lake/latest_output_tables/adverts_ojd_daps_extract.parquet"
ojo_s3_file_descriptions: "s3://open-jobs-lake/latest_output_tables/descriptions.parquet"
ojo_s3_file_salaries: "s3://open-jobs-lake/latest_output_tables/salaries_ojd_daps_extract.parquet"
ojo_s3_file_locations: "s3://open-jobs-lake/latest_output_tables/locations_ojd_daps_extract.parquet"
ojo_s3_file_skills: "s3://open-jobs-lake/latest_output_tables/skills_ojd_daps_extract.parquet"
ojo_random_sample_size: 100000

job_adverts:
  job_id_key: "id"
  job_text_key: "job_text"
  job_title_key: "job_title"
  company_name_key: "company_name"
skills:
  skills_config_name: "extract_green_skills_esco"
  load_skills: True
  load_skills_embeddings: True
  load_taxonomy_embeddings: True
  skills_output: "outputs/data/green_skill_lists/skills_data_ojo_mixed_20230815.json"
  skill_embeddings_output: "outputs/data/green_skill_lists/extracted_skills_embeddings_20230816.json"
  green_tax_embedding_path: "outputs/data/green_skill_lists/green_esco_embeddings_20230815.json"
occupations:
  local: False
  embeddings_output_dir: "outputs/data/green_occupations/soc_matching/"
  batch_size: 500
  match_top_n: 10
  sim_threshold: 0.67
  top_n_sim_threshold: 0.5
  minimum_n: 3
  minimum_prop: 0.5
  save_embeds: True
industries:
