ner_model_path: "outputs/models/ner_model/20230808/"
taxonomy_name: "green_esco"
taxonomy_path: "outputs/data/green_skill_lists/green_esco_data_formatted_20231129.csv"
clean_job_ads: True
min_multiskill_length: 75
taxonomy_embedding_file_name: "outputs/data/green_skill_lists/green_esco_embeddings_20231129.json"
prev_skill_matches_file_name: ""
hard_labelled_skills_file_name: ""
hier_name_mapper_file_name: ""
num_hier_levels: 0
skill_type_dict:
  { "skill_types": ["preferredLabel", "altLabels"], "hier_types": [] }
match_thresholds_dict:
  { "skill_match_thresh": 0.7 }
  #"top_tax_skills": { 1: 0.5, 2: 0.5, 3: 0.5 },
  #"max_share": { 1: 0, 2: 0.2, 3: 0.2 },
skill_name_col: "description"
skill_id_col: "id"
skill_hier_info_col: "hierarchy_levels"
skill_type_col: "type"
