job_id_col: "job_id"
production: "True"
config: "base"
skills_date_stamp: "20241118"
skill_metrics_name: "ojo_all_skills_green_measures_skill_metrics.parquet"
green_skills_exploded_name: "ojo_all_skills_green_measures_exploded_green.parquet"
all_skills_exploded_name: "ojo_all_skills_exploded.parquet"
occ_date_stamp: "20241118"
occ_file_name: "ojo_all_occupation_green_measures_production_True.parquet"
ind_date_stamp: "20241115"
ind_file_name: "ojo_all_industry_green_measures_production_True.parquet"
deduplicated_data_dir: "s3://prinz-green-jobs/outputs/data/ojo_application/deduplicated_sample/20241114/"
dedupe_salary_name: "latest_update_20241114_salaries.parquet"
dedupe_location_name: "latest_update_20241114_locations.parquet"
dedupe_key_columns_name: "latest_update_20241114_key_columns.parquet"
data_type: "all"
skill_match_thresh: 0.7
bad_coef_threshold: 0.2
min_num_job_ads: 50
analysis_files:
  agg_soc_date_stamp: "20241121"
  agg_sic_date_stamp: "20241121"
  agg_region_date_stamp: "20241121"
  occ_most_similar_date: "20241121"
