job_id_col: "job_id"
production: "True"
config: "base"
skills_date_stamp: "20241118"
skills_file_name: "ojo_all_skills_green_measures_production_True.parquet"
occ_date_stamp: "20241118"
occ_file_name: "ojo_all_occupation_green_measures_production_True.parquet"
ind_date_stamp: "20241115"
ind_file_name: "ojo_all_industry_green_measures_production_True.parquet"
data_type: "all"
skill_match_thresh: 0.7
bad_coef_threshold: 0.2
min_num_job_ads: 50
analysis_files:
  agg_soc_date_stamp: "20240404"
  agg_sic_date_stamp: "20240404"
  agg_region_date_stamp: "20240404"
  occ_most_similar_date: "20240404"
