job_id_col: "job_id"
production: "True"
config: "base"
skills_date_stamp: "20231204"
occ_date_stamp: "20231127"
ind_date_stamp: "20231205"
data_type: "large"
skill_match_thresh: 0.7
bad_coef_threshold: 0.2
min_num_job_ads: 50
analysis_files:
  agg_soc_date_stamp: "20240112"
  agg_sic_date_stamp: "20240112"
  agg_region_date_stamp: "20240112"
  occ_most_similar_date: "20240112"
