job_id_col: "job_id"
production: "True"
config: "base"
skills_date_stamp: "20240220"
skills_file_name: "all_ojo_large_sample_skills_green_measures_production_True.csv"
occ_date_stamp: "20240313"
occ_file_name: "ojo_large_sample_occupation_green_measures_production_true.csv"
ind_date_stamp: "20240216"
ind_file_name: "ojo_large_sample_industry_green_measures_production_True.csv"
data_type: "all"
skill_match_thresh: 0.7
bad_coef_threshold: 0.2
min_num_job_ads: 50
analysis_files:
  agg_soc_date_stamp: "20240314"
  agg_sic_date_stamp: "20240314"
  agg_region_date_stamp: "20240314"
  occ_most_similar_date: "20240314"
