name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os:
          - name: ubuntu
            host: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: (ubuntu) Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
          python -m spacy download en_core_web_sm
      - name: (ubuntu) Test with pytest
        run: |
          pytest --verbose
