name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]
        os:
          - name: ubuntu
            host: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: (ubuntu) Install dependencies
        if: runner.os != 'windows'
        run: |
          python -m pip install --upgrade pip
          conda create --n testenv python=${{ matrix.python-version }}
          conda activate testenv
          pip install -e . 
          python -m spacy download en_core_web_sm
          conda install -c pytorch faiss-cpu=1.7.4 mkl=2021 blas=1.0=mkl
      - name: (ubuntu) Test with pytest
        if: runner.os != 'windows'
        run: |
          pytest --verbose
