name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os:
          - name: ubuntu
            host: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: (ubuntu) Install pip dependencies
        if: runner.os != 'windows'
        run: |
          python -m pip install --upgrade pip
          pip install -e . 
          python -m spacy download en_core_web_sm
      - name: (ubuntu) Install conda dependencies
        if: runner.os != 'windows'
        run: |
          conda config --set channel_priority flexible
          conda install -c pytorch faiss-cpu=1.7.4 mkl=2021 blas=1.0=mkl -y
      - name: (ubuntu) Test with pytest
        if: runner.os != 'windows'
        run: |
          pytest --verbose
